services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2026.1.3
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - './homeassistant/config:/config'
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  matter-hub:
    image: ghcr.io/riddix/home-assistant-matter-hub:1.10.8
    container_name: matter-hub
    restart: unless-stopped
    network_mode: host
    # default Port is 8482
    env_file:
      - .env
    volumes:
      - $PWD/home-assistant-matter-hub:/data
  music-assistant:
    image: ghcr.io/music-assistant/server:2.7.6
    container_name: musicassistant
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: "host"
    volumes:
      - ./musicassistant/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=error
