services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - './homeassistant/config:/config'
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
