services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - './homeassistant/config:/config'
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  matter-hub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    container_name: matter-hub
    restart: unless-stopped
    network_mode: host
    environment: # more options can be found in the configuration section
      - HAMH_HOME_ASSISTANT_URL=http://192.168.178.113:8123/
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=ey....U
      - HAMH_LOG_LEVEL=info
      - HAMH_HTTP_PORT=8482
    volumes:
      - $PWD/home-assistant-matter-hub:/data
