services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.28.1
    container_name: freshrss
    environment:
      # PUID und PGID deines Benutzers (z.B. 1000 f체r den Standard-Pi-Nutzer)
      - PUID=1000
      - PGID=1000
      # W채hle deine Zeitzone (z.B. Europe/Berlin)
      - TZ=Europe/Berlin
    volumes:
      # Pfad zum lokalen Speicherort der Konfiguration (wichtig f체r persistente Daten)
      - ./config:/config
    ports:
      # Externe Port:Interner Port (Hier: Zugriff 체ber Port 8080)
      - 8080:80
    restart: unless-stopped
